version = 1

[[annotations]]
path = [
    "static/service-descriptions/*.jsonld",
    "static/service-descriptions/*.nt",
    "static/service-descriptions/*.rdf",
    "static/service-descriptions/*.html",
    "static/service-descriptions/*.ttl",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
