name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

env:
  COVERAGE_REPORT_PATH: htmlcov

jobs:
  CheckCoverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    
    - name: Install dependencies
      run: uv sync --dev

    - name: Start test database
      run: ./test/start_test_db.sh

    - name: Run tests with coverage
      run: |
        echo "COVERAGE=$(uv run pytest --cov=src --cov-report=term-missing --cov-report=html | tee /dev/stderr | grep TOTAL | awk '{print $4}')" >> $GITHUB_ENV

    - name: Stop test database
      if: always()
      run: ./test/stop_test_db.sh

    - name: Upload coverage artifact
      if: matrix.python-version == '3.10'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ env.COVERAGE_REPORT_PATH }}
        
    - name: Generate coverage badge
      if: matrix.python-version == '3.10'
      run: |
        COVERAGE_NUM=$(echo ${{ env.COVERAGE }} | sed 's/%//')
        
        if (( $(echo "$COVERAGE_NUM >= 90" | bc -l) )); then
          COLOR="green"
        elif (( $(echo "$COVERAGE_NUM >= 75" | bc -l) )); then
          COLOR="yellow"
        elif (( $(echo "$COVERAGE_NUM >= 60" | bc -l) )); then
          COLOR="orange"
        else
          COLOR="red"
        fi
        
        echo "BADGE_COLOR=$COLOR" >> $GITHUB_ENV
      
    - name: Create coverage badge
      if: matrix.python-version == '3.10'
      run: |
        # Create SVG badge directly without external dependencies
        cat > test/coverage-badge.svg << EOF
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="104" height="20" role="img" aria-label="Coverage: ${{ env.COVERAGE }}">
          <title>Coverage: ${{ env.COVERAGE }}</title>
          <linearGradient id="s" x2="0" y2="100%">
            <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
            <stop offset="1" stop-opacity=".1"/>
          </linearGradient>
          <clipPath id="r">
            <rect width="104" height="20" rx="3" fill="#fff"/>
          </clipPath>
          <g clip-path="url(#r)">
            <rect width="61" height="20" fill="#555"/>
            <rect x="61" width="43" height="20" fill="${{ env.BADGE_COLOR }}"/>
            <rect width="104" height="20" fill="url(#s)"/>
          </g>
          <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
            <text aria-hidden="true" x="315" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="510">Coverage</text>
            <text x="315" y="140" transform="scale(.1)" fill="#fff" textLength="510">Coverage</text>
            <text aria-hidden="true" x="815" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="330">${{ env.COVERAGE }}</text>
            <text x="815" y="140" transform="scale(.1)" fill="#fff" textLength="330">${{ env.COVERAGE }}</text>
          </g>
        </svg>
        EOF
        
    - name: Commit coverage badge
      if: matrix.python-version == '3.10'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add test/coverage-badge.svg
        git diff --staged --quiet || git commit -m "Update coverage badge"
        git push